### ISSUE TITLE
npm run test failed

### ISSUE THREAD

**Issue by Jmunapo** [t04glovern/cryptodoggies#1]
`> cryptodoggies@1.0.0 test C:\Crypto\Crypto-Udemy\cryptodoggies-base
> scripts/test.sh

'scripts' is not recognized as an internal or external command,
operable program or batch file.`

Plartform
Win 10
npm v5.8.0
node v9.9.0

Log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ACER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@5.8.0
3 info using node@v9.9.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle cryptodoggies@1.0.0~pretest: cryptodoggies@1.0.0
6 info lifecycle cryptodoggies@1.0.0~test: cryptodoggies@1.0.0
7 verbose lifecycle cryptodoggies@1.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle cryptodoggies@1.0.0~test: PATH: C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Crypto\Crypto-Udemy\cryptodoggies-base\node_modules\.bin;C:\Users\ACER\gcc\bin;C:\Users\ACER\gcc\libexec\gcc\x86_64-pc-mingw32\4.8.2;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\PuTTY\;C:\curl;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\ACER\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\ACER\AppData\Local\Programs\Python\Python36-32\;C:\Users\ACER\AppData\Local\Microsoft\WindowsApps;C:\Users\ACER\AppData\Roaming\Composer\vendor\bin;C:\Users\ACER\AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Java\jdk1.8.0_144\bin;C:\Users\ACER\AppData\Local\Android\sdk\tools;C:\Users\ACER\AppData\Local\Android\sdk\platform-tools;C:\Users\ACER\AppData\Local\Microsoft\WindowsApps;C:\Users\ACER\AppData\Roaming\npm;C:\Users\ACER\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle cryptodoggies@1.0.0~test: CWD: C:\Crypto\Crypto-Udemy\cryptodoggies-base
10 silly lifecycle cryptodoggies@1.0.0~test: Args: [ '/d /s /c', 'scripts/test.sh' ]
11 silly lifecycle cryptodoggies@1.0.0~test: Returned: code: 1  signal: null
12 info lifecycle cryptodoggies@1.0.0~test: Failed to exec test script
13 verbose stack Error: cryptodoggies@1.0.0 test: `scripts/test.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid cryptodoggies@1.0.0
15 verbose cwd C:\Crypto\Crypto-Udemy\cryptodoggies-base
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ACER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v9.9.0
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error cryptodoggies@1.0.0 test: `scripts/test.sh`
22 error Exit status 1
23 error Failed at the cryptodoggies@1.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by t04glovern** [comment]
Try running `./scripts/test.sh` instead of _npm run test_, its an issue with file structures on Windows vs Unix.

**Comment by Jmunapo** [comment]
I'm getting this => 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ACER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'scripts/test.sh' ]
2 info using npm@5.8.0
3 info using node@v9.9.0
4 verbose stack Error: missing script: scripts/test.sh
4 verbose stack     at run (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:364:12
4 verbose stack     at C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5 verbose cwd C:\Crypto\Crypto-Udemy\cryptodoggies-base
6 verbose Windows_NT 10.0.15063
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ACER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "scripts/test.sh"
8 verbose node v9.9.0
9 verbose npm  v5.8.0
10 error missing script: scripts/test.sh
11 verbose exit [ 1, true ]

**Comment by t04glovern** [comment]
Are you using GitBash to run the commands? Install Git for Windows and then open GitBash (comes with git for windows). It's hard to tell from your logs if you're using the default command prompt or not sorry.

![image](https://user-images.githubusercontent.com/7262516/40355441-f84dad18-5de8-11e8-8c60-87e894357848.png)

**Comment by Jmunapo** [comment]
Thanks, I was using VSs default cmd
![test](https://user-images.githubusercontent.com/28527609/40356451-583c2504-5db9-11e8-994c-59021d00dedb.PNG)

Now this is the problem even on running compile

**Comment by t04glovern** [comment]
Two things:

1. have you installed the dependencies:
    - npm install -g truffle

2. How far into the course are you? Trying to run test on the empty repo probably won't work; just want to check you've progressed far enough into the course that scripts/test.sh is possible.
